scilus/nf-neuro

nf-test.config

Path to plugins definition is incorrect, needs to be fixed for nf-test to run
Try to run a test.

Fix nf-test config

---

.github/workflows/run_checks_suite.yml
.github/workflows/test_component.yml

Test don't run because `nf-test` version on runner is below `0.9.0`.
Try to test a module in a PR. Insta-fail !

[WIP] Hotpatch runners nf-test version

---

.github/workflows/test_component.yml
subworkflows/nf-neuro/load_test_data/main.nf
tests/nextflow.config

Just remove last nf-scil pieces laying around.

Remove last nf-scil references

---

.devcontainer/Dockerfile
.devcontainer/updateContentCommand.sh
config/resources.config
nf-test.config
tests/config/nextflow.config
tests/nextflow.config

Two things :
- fix resources when running tests and nf-core commands calling nextflow
- update java

Fix computing resources and java

---

.github/workflows/run_checks_suite.yml
modules/nf-neuro/registration/easyreg/main.nf
modules/nf-neuro/registration/easyreg/meta.yml
subworkflows/nf-neuro/registration/main.nf
subworkflows/nf-neuro/registration/meta.yml
subworkflows/nf-neuro/registration/tests/main.nf.test
subworkflows/nf-neuro/registration/tests/main.nf.test.snap
subworkflows/nf-neuro/registration/tests/nextflow_easyreg.config

Add the synthbet option to preproc_t1
- `processing.zip`

[Improvement] add easyreg option to subworkflow/registration 

---

modules/nf-neuro/registration/anattodwi/main.nf
modules/nf-neuro/registration/anattodwi/tests/main.nf.test
modules/nf-neuro/registration/anattodwi/tests/main.nf.test.snap
modules/nf-neuro/registration/ants/main.nf
modules/nf-neuro/registration/ants/tests/main.nf.test
modules/nf-neuro/registration/ants/tests/main.nf.test.snap
modules/nf-neuro/registration/ants/tests/nextflow.config
modules/nf-neuro/registration/antsapplytransforms/main.nf
modules/nf-neuro/registration/antsapplytransforms/tests/main.nf.test.snap
subworkflows/nf-neuro/bundle_seg/tests/main.nf.test.snap
subworkflows/nf-neuro/registration/tests/main.nf.test
subworkflows/nf-neuro/registration/tests/main.nf.test.snap
subworkflows/nf-neuro/registration/tests/nextflow_easyreg.config

Update registration modules with Alex's changes. #14
Also made several changes to the test data used to make the test runs faster.

[ENH] Update registration modules

---

modules/nf-neuro/io/nii2dcm/environment.yml
modules/nf-neuro/io/nii2dcm/main.nf
modules/nf-neuro/io/nii2dcm/meta.yml
modules/nf-neuro/io/nii2dcm/tests/main.nf.test
modules/nf-neuro/io/nii2dcm/tests/nextflow.config
modules/nf-neuro/io/nii2dcm/tests/tags.yml
tests/test_data.json

New module to convert a nii image into DCM format.
dicom.zip and b0.zip

nii2dcm module

---

modules/nf-neuro/image/convert/environment.yml
modules/nf-neuro/image/convert/main.nf
modules/nf-neuro/image/convert/meta.yml
modules/nf-neuro/image/convert/tests/main.nf.test
modules/nf-neuro/image/convert/tests/main.nf.test.snap
modules/nf-neuro/image/convert/tests/nextflow_float32.config
modules/nf-neuro/image/convert/tests/nextflow_uint8.config
modules/nf-neuro/image/convert/tests/tags.yml

New module to convert an image into a specific datatype.
T1w.zip

[Module] New utility module to convert images into a specific datatype

---

modules/nf-neuro/betcrop/cropvolume/main.nf
modules/nf-neuro/preproc/n4/main.nf

Answer issue 41

---

modules/nf-neuro/registration/anattodwi/main.nf
modules/nf-neuro/registration/anattodwi/tests/main.nf.test.snap
subworkflows/nf-neuro/registration/tests/main.nf.test.snap

Fix `ANTs` version in `registration/anattodwi`. (#41)

fix `ants` version in anattodwi

---

modules/nf-neuro/betcrop/cropvolume/main.nf

fix optional touch of boundingbox in cropvolume

---

modules/nf-neuro/segmentation/freesurferseg/main.nf
modules/nf-neuro/segmentation/freesurferseg/tests/main.nf.test.snap
modules/nf-neuro/segmentation/fsreconall/main.nf
modules/nf-neuro/segmentation/fsreconall/tests/main.nf.test.snap
subworkflows/nf-neuro/anatomical_segmentation/tests/main.nf.test.snap

* Update container version in `segmentation/freesurferseg` to `scilpy` 2.0.2. Also, update how the version is fetched using the dynamic method.
* Update how the version is fetched in `segmentation/fsreconall`.  
(#41)

Update versions in `segmentation/freesurferseg` and `segmentation/fsreconall`

---

modules/nf-neuro/preproc/eddy/main.nf
modules/nf-neuro/preproc/eddy/tests/main.nf.test
modules/nf-neuro/preproc/eddy/tests/main.nf.test.snap
subworkflows/nf-neuro/preproc_dwi/main.nf
subworkflows/nf-neuro/preproc_dwi/tests/main.nf.test
subworkflows/nf-neuro/preproc_dwi/tests/main.nf.test.snap
subworkflows/nf-neuro/topup_eddy/main.nf
subworkflows/nf-neuro/topup_eddy/tests/main.nf.test
subworkflows/nf-neuro/topup_eddy/tests/main.nf.test.snap
tests/test_data.json

Revert "[ENH] Update topup_eddy subworkflows and eddy module"

---

subworkflows/nf-neuro/preproc_t1/main.nf

Revert "[ENH] Update subworkflow preproc_t1"

---

subworkflows/nf-neuro/load_test_data/main.nf

Redownload on first zip error. add verbosity to error messages

---

.github/workflows/update_main.yml
docs/astro/convert_modules.py
docs/astro/convert_subworkflows.py

Add some files for the website workflows to run. I pass it silently, will open another PR once working to inform and review

[WIP] Add documentation requirements for website

---

modules/nf-neuro/connectivity/afdfixel/environment.yml
modules/nf-neuro/connectivity/afdfixel/main.nf
modules/nf-neuro/connectivity/afdfixel/meta.yml
modules/nf-neuro/connectivity/afdfixel/tests/main.nf.test
modules/nf-neuro/connectivity/afdfixel/tests/main.nf.test.snap
modules/nf-neuro/connectivity/afdfixel/tests/nextflow.config
modules/nf-neuro/connectivity/afdfixel/tests/tags.yml

New module to compute AFD Fixel from a decomposed tractogram.
`connectivity.zip`

[MODULE] New `connectivity/afdfixel` module.

---

docs/astro/convert_modules.py
docs/astro/convert_subworkflows.py

To render the doc website correctly, we need to change some things.

[Hotfix] Put modules in their category directory (documentation)

---

tests/test_data.json

New test dataset : `dwi_mouse.zip`

Add mice dwi test dataset

---

.github/workflows/test_component.yml

We need to update actions/cache
Run tests on any PR (except #117).

[HOTFIX] Update cache action

---

docs/cspell/neuroscience.txt
modules/nf-neuro/reconst/shsignal/environment.yml
modules/nf-neuro/reconst/shsignal/main.nf
modules/nf-neuro/reconst/shsignal/meta.yml
modules/nf-neuro/reconst/shsignal/tests/main.nf.test
modules/nf-neuro/reconst/shsignal/tests/main.nf.test.snap
modules/nf-neuro/reconst/shsignal/tests/tags.yml

New module to compute `SH` on the `DWI signal`
- DWIss1000-dir32.zip
- segmentation.zip

[MODULE] RECONST_SHSIGNAL

---

modules/nf-neuro/stats/metricsinroi/environment.yml
modules/nf-neuro/stats/metricsinroi/main.nf
modules/nf-neuro/stats/metricsinroi/meta.yml
modules/nf-neuro/stats/metricsinroi/tests/main.nf.test
modules/nf-neuro/stats/metricsinroi/tests/main.nf.test.snap
modules/nf-neuro/stats/metricsinroi/tests/nextflow.config
modules/nf-neuro/stats/metricsinroi/tests/nextflow_label.config
modules/nf-neuro/stats/metricsinroi/tests/tags.yml

Add stats metrics in roi

---

modules/nf-neuro/denoising/mppca/main.nf

change container for scilus/latest

[Improve] module denoising/mppca

---

modules/nf-neuro/reconst/dtimetrics/main.nf

Quick modification after playing with the test data and a discussion with Maxime.

Add ransac correction for ad md and rd

---

tests/test_data.json

Simple dataset with just enough to test tractometry

Add whole brain test data for tractometry

---

modules/nf-neuro/stats/mergejson/environment.yml
modules/nf-neuro/stats/mergejson/main.nf
modules/nf-neuro/stats/mergejson/meta.yml
modules/nf-neuro/stats/mergejson/tests/main.nf.test
modules/nf-neuro/stats/mergejson/tests/main.nf.test.snap
modules/nf-neuro/stats/mergejson/tests/nextflow.config
modules/nf-neuro/stats/mergejson/tests/tags.yml

added merge json module, we're missing a module to merge stats json from several subjects together, globally it's for tractometry_flow output. It generates JSON and xlsx output.
For snapshots of xlsx files I take only the name because the generation of these files is highly unstable.

[Module] Add module to merge json

---

docs/astro/convert_modules.py
modules/nf-neuro/tracking/localtracking/main.nf
modules/nf-neuro/tracking/localtracking/meta.yml
modules/nf-neuro/tracking/localtracking/tests/main.nf.test.snap
modules/nf-neuro/tracking/pfttracking/main.nf
modules/nf-neuro/tracking/pfttracking/meta.yml
modules/nf-neuro/tracking/pfttracking/tests/main.nf.test.snap
subworkflows/nf-neuro/tractoflow/tests/main.nf.test.snap

Fix PFT seeding mask

---

.ecrc
docs/astro/convert_module.py
docs/astro/convert_subworkflow.py

Fix indentation of the produced markdown

[HOTFIX] fix indentation problems

---

README.md

- Add publications so people can start citing once they start using
- Revamp README to direct people to website more quickly
- Remove deduplication from website

Add publications and revamp README

---

.github/workflows/run_checks_suite.yml

[WIP] Update runners

---

.github/workflows/lint_component.yml
docs/astro/templates/module.md.jinja2

Linting workflow need to give fill path to module from repo root
Provide a full step-by-step guide to reproduce the bug.

[HOTFIX] linting workflow

---

docs/astro/convert_module.py
docs/astro/convert_subworkflow.py
docs/astro/templates/module.md.jinja2
docs/astro/templates/subworkflow.md.jinja2

API rendering using jinja2 add bugs in the template.
Provide a full step-by-step guide to reproduce the bug.

[HOTFIX] update API structure

---

modules/nf-neuro/reconst/qball/environment.yml
modules/nf-neuro/reconst/qball/main.nf
modules/nf-neuro/reconst/qball/meta.yml
modules/nf-neuro/reconst/qball/tests/main.nf.test
modules/nf-neuro/reconst/qball/tests/main.nf.test.snap
modules/nf-neuro/reconst/qball/tests/nextflow.config
modules/nf-neuro/reconst/qball/tests/nextflow_light.config
modules/nf-neuro/reconst/qball/tests/tags.yml

[MODULE] New Qball module

---

modules/nf-neuro/reconst/diffusivitypriors/main.nf
modules/nf-neuro/reconst/diffusivitypriors/tests/main.nf.test.snap
modules/nf-neuro/reconst/dtimetrics/main.nf
modules/nf-neuro/reconst/dtimetrics/tests/main.nf.test.snap
modules/nf-neuro/reconst/freewater/main.nf
modules/nf-neuro/reconst/freewater/meta.yml
modules/nf-neuro/reconst/freewater/tests/main.nf.test
modules/nf-neuro/reconst/freewater/tests/main.nf.test.snap
modules/nf-neuro/reconst/freewater/tests/nextflow_compute_only.config
modules/nf-neuro/reconst/frf/main.nf
modules/nf-neuro/reconst/frf/tests/main.nf.test.snap
modules/nf-neuro/reconst/ihmt/main.nf
modules/nf-neuro/reconst/ihmt/tests/main.nf.test.snap
modules/nf-neuro/reconst/meanfrf/main.nf
modules/nf-neuro/reconst/meanfrf/tests/main.nf.test.snap
modules/nf-neuro/reconst/noddi/main.nf
modules/nf-neuro/reconst/noddi/tests/main.nf.test.snap
modules/nf-neuro/reconst/shmetrics/main.nf
modules/nf-neuro/reconst/shmetrics/tests/main.nf.test
modules/nf-neuro/reconst/shmetrics/tests/main.nf.test.snap
modules/nf-neuro/reconst/shsignal/main.nf
modules/nf-neuro/reconst/shsignal/tests/main.nf.test.snap
subworkflows/nf-neuro/tractoflow/tests/main.nf.test.snap

Write a clear and concise description of what the improvement is.
Provide a full step-by-step guide to test your improvement.

update containers - module reconst

---

modules/nf-neuro/tractogram/densitymap/main.nf
modules/nf-neuro/tractogram/densitymap/meta.yml
modules/nf-neuro/tractogram/densitymap/tests/main.nf.test.snap
modules/nf-neuro/tractogram/densitymap/tests/nextflow_mask.config
modules/nf-neuro/tractogram/math/main.nf
modules/nf-neuro/tractogram/math/tests/main.nf.test.snap
modules/nf-neuro/tractogram/removeinvalid/main.nf
modules/nf-neuro/tractogram/removeinvalid/meta.yml
modules/nf-neuro/tractogram/removeinvalid/tests/main.nf.test.snap
modules/nf-neuro/tractogram/resample/main.nf
modules/nf-neuro/tractogram/resample/meta.yml
modules/nf-neuro/tractogram/resample/tests/main.nf.test.snap

Write a clear and concise description of what the improvement is.
Provide a full step-by-step guide to test your improvement.

update containers - module tractogram 
