modules/nf-neuro/registration/convert/environment.yml, modules/nf-neuro/registration/convert/main.nf, modules/nf-neuro/registration/convert/meta.yml, modules/nf-neuro/registration/convert/tests/main.nf.test, modules/nf-neuro/registration/convert/tests/main.nf.test.snap, modules/nf-neuro/registration/convert/tests/nextflow_antsfs.config, modules/nf-neuro/registration/convert/tests/nextflow_default.config, modules/nf-neuro/registration/convert/tests/nextflow_fsants.config, modules/nf-neuro/registration/convert/tests/nextflow_fslants.config, modules/nf-neuro/registration/convert/tests/nextflow_fslfs.config, modules/nf-neuro/registration/convert/tests/tags.yml
Add the synthbet option to preproc_t1Warp conversion module - designed initially to convert freesurfer registration warp (affine and deform) to ants-itk. Then decided to generalize the module for all cases possible. Receives one affine matrix, one deform warp, source and target images for orientation (and freesurfer licence) and outputs converted affine and deform.
- `freeurfer.zip`
- `freesurfer_relice.zip`
- `freesurfer_transforms.zip`
=> [New module] Freesurfer registration/convert

.github/workflows/run_checks_suite.yml, modules/nf-neuro/registration/synthregistration/environment.yml, modules/nf-neuro/registration/synthregistration/main.nf, modules/nf-neuro/registration/synthregistration/meta.yml, modules/nf-neuro/registration/synthregistration/tests/main.nf.test, modules/nf-neuro/registration/synthregistration/tests/main.nf.test.snap, modules/nf-neuro/registration/synthregistration/tests/nextflow.config, modules/nf-neuro/registration/synthregistration/tests/tags.yml
Initial module PR for registration tool using Freesurfer synthmorph
=> [New module] Freesurfer synthregistration

.github/workflows/run_checks_suite.yml, modules/nf-neuro/segmentation/synthseg/main.nf, modules/nf-neuro/segmentation/synthseg/meta.yml, modules/nf-neuro/segmentation/synthseg/tests/main.nf.test, modules/nf-neuro/segmentation/synthseg/tests/main.nf.test.snap, subworkflows/nf-neuro/anatomical_segmentation/main.nf, subworkflows/nf-neuro/anatomical_segmentation/meta.yml, subworkflows/nf-neuro/anatomical_segmentation/tests/main.nf.test, subworkflows/nf-neuro/anatomical_segmentation/tests/main.nf.test.snap, subworkflows/nf-neuro/anatomical_segmentation/tests/nextflow_synthseg.config
Add the synthseg option to anatomical_segmentation
- `T1w.zip`
- `freesurfer_nifti.zip`
Pass synthseg module to run and debug tests
=> [Improvement] add synthseg option to anatomical_segmentation

modules/nf-neuro/image/resample/main.nf, modules/nf-neuro/image/resample/meta.yml, modules/nf-neuro/image/resample/tests/main.nf.test.snap, subworkflows/nf-neuro/preproc_dwi/tests/main.nf.test.snap, subworkflows/nf-neuro/preproc_t1/tests/main.nf.test, subworkflows/nf-neuro/preproc_t1/tests/main.nf.test.snap, subworkflows/nf-neuro/preproc_t1/tests/nextflow_2.config
Update image/resample with Alex's changes + update tests. #14
=> [ENH] Update image/resample 

modules/nf-neuro/image/burnvoxels/environment.yml, modules/nf-neuro/image/burnvoxels/main.nf, modules/nf-neuro/image/burnvoxels/meta.yml, modules/nf-neuro/image/burnvoxels/tests/main.nf.test, modules/nf-neuro/image/burnvoxels/tests/main.nf.test.snap, modules/nf-neuro/image/burnvoxels/tests/tags.yml
New module to burn an image with multiple masks.
tractometry.zip 
=> New module to burn voxels

modules/nf-neuro/segmentation/synthseg/main.nf, subworkflows/nf-neuro/anatomical_segmentation/main.nf, subworkflows/nf-neuro/anatomical_segmentation/tests/main.nf.test, subworkflows/nf-neuro/anatomical_segmentation/tests/main.nf.test.snap
Fixed an issue where using .join() function would not work in the context of a workflow
=> [ENH] Fix synthseg inputs in subworkflow

modules/nf-neuro/bundle/recognize/main.nf, subworkflows/nf-neuro/bundle_seg/main.nf, subworkflows/nf-neuro/bundle_seg/tests/main.nf.test
Fixed running subworkflow with paing atlas. Logic based on param instead of channel
=> [ENH] Fix bundleseg atlas

modules/nf-neuro/preproc/topup/main.nf, modules/nf-neuro/utils/extractb0/main.nf
Modules changes : 
Update versions in utils/extractb0. (@Manonedde)
Add the correct prefix_topup in the stub section in the topup module. (@Manonedde)
Everything is good locally...
=> correction for extractb0 scilpy version and topup stub prefix

.github/workflows/run_checks_suite.yml, modules/nf-neuro/betcrop/synthbet/main.nf, modules/nf-neuro/betcrop/synthbet/tests/main.nf.test.snap, modules/nf-neuro/betcrop/synthbet/tests/nextflow.config, subworkflows/nf-neuro/preproc_t1/tests/main.nf.test.snap
=> change version container synthbet (Answer issue 41)

modules/nf-neuro/registration/antsapplytransforms/main.nf, modules/nf-neuro/registration/antsapplytransforms/meta.yml, modules/nf-neuro/registration/antsapplytransforms/tests/main.nf.test, modules/nf-neuro/registration/antsapplytransforms/tests/main.nf.test.snap, modules/nf-neuro/registration/antsapplytransforms/tests/nextflow.config
Splitted the transform files in input into two different inputs, making it easier when combining it with other modules. Also, cleaned up the module and added a `-stub-run` test case.
=> Split transforms into 2 inputs and update versions in `registrations/antsapplytransforms`

modules/nf-neuro/registration/convert/main.nf, modules/nf-neuro/registration/convert/meta.yml, modules/nf-neuro/registration/convert/tests/main.nf.test, modules/nf-neuro/registration/convert/tests/main.nf.test.snap, modules/nf-neuro/registration/synthregistration/main.nf, modules/nf-neuro/registration/synthregistration/meta.yml, modules/nf-neuro/registration/synthregistration/tests/main.nf.test, modules/nf-neuro/registration/synthregistration/tests/main.nf.test.snap, subworkflows/nf-neuro/registration/main.nf, subworkflows/nf-neuro/registration/meta.yml, subworkflows/nf-neuro/registration/tests/main.nf.test, subworkflows/nf-neuro/registration/tests/main.nf.test.snap, subworkflows/nf-neuro/registration/tests/nextflow_synthregistration.config
subworkflow/registration:
- add synthregistration optionality to subworkflow
- add specific test for synthregistration
modules/synthregistration:
- change output structure to tuple transfo_image containing both transforms
- add python package access. 
module/convert:
- add optionality to affine conversion. If no affine is provided, skips conversion. Synthmorph output include affine initialization in its deform output.
- change output order
=> [ENH] Update registration subworkflows and modules

modules/nf-neuro/preproc/eddy/main.nf, modules/nf-neuro/preproc/eddy/tests/main.nf.test, modules/nf-neuro/preproc/eddy/tests/main.nf.test.snap, subworkflows/nf-neuro/preproc_dwi/main.nf, subworkflows/nf-neuro/preproc_dwi/tests/main.nf.test, subworkflows/nf-neuro/preproc_dwi/tests/main.nf.test.snap, subworkflows/nf-neuro/topup_eddy/main.nf, subworkflows/nf-neuro/topup_eddy/tests/main.nf.test, subworkflows/nf-neuro/topup_eddy/tests/main.nf.test.snap, tests/test_data.json
Continuation of #26
subworkflow/topup_eddy:
copy alex's changes for tractoflow
module/preproc/eddy:
- change bval output name: had problem further in the flow caused by lack ox fil extension
=> [ENH] Update topup_eddy subworkflows and eddy module

modules/nf-neuro/betcrop/antsbet/main.nf, modules/nf-neuro/betcrop/antsbet/tests/main.nf.test, modules/nf-neuro/betcrop/antsbet/tests/main.nf.test.snap
I added the trap function to catch the error code for antsBrainExtraction.sh. The function has to be placed after we fetch the versions and touch the files. If not, for some reason, it also catches the output files. Link to #40
=> #40 - Catch antsBrainExtraction.sh exit error code in stub-run + add stub test

modules/nf-neuro/betcrop/synthbet/main.nf, modules/nf-neuro/betcrop/synthbet/tests/main.nf.test, modules/nf-neuro/betcrop/synthbet/tests/main.nf.test.snap
=> #40 - Catch exit code error for `betcrop/synthstrip` + stub run test

modules/nf-neuro/registration/synthregistration/main.nf, modules/nf-neuro/registration/synthregistration/tests/nextflow.config, subworkflows/nf-neuro/registration/tests/nextflow_synthregistration.config, tests/config/nextflow.config
All tests seem to run well, except for `synthregistration`. Other ML based models seem to run correctly on the `bigmem` runners, so the cluster configurtion seems ok. There appears to be a **memory leak** inside of `synthregistration`, or maybe it doesn't manage resources by construction.
To try to prevent this, I created a new profile for runners, applied by `nextflow` through `tests/config/nextflow.config`, that sets a memory limit on the containers spawned by docker. Maybe this will restrict `synthregistration` gobbling the whole RAM.
Current status of any tests including `synthregistration` in a PR is failed.
=> Restrict RAM on containers through nextflow profile

modules/nf-neuro/preproc/topup/main.nf
Acquisitions on Phillips scanners were returning weird concatenated b0s in topup due to the multiplier not being properly used. Forcing `--data_type float32` in the concatenate steps solves the issue. See images below:
**Without enforcing data type:**
**With enforcing the data type:**
=> Fix data type for phillips acquisition in topup module

modules/nf-neuro/registration/ants/main.nf, modules/nf-neuro/registration/ants/tests/main.nf.test, modules/nf-neuro/registration/ants/tests/main.nf.test.snap
The stub section of `registration/ants` was not updated to catch the exit code of the ants scripts (returning a non-zero exit code when calling the help)—I also added a test for a `-stub-run.`
=> Fix stub section of `registration/ants` + add stub-run test

.github/workflows/run_checks_suite.yml
…to-date commit)
Running the `update_main` github workflow fails if done manually, since **head ref** and **base ref** are the same.
Launch the `update_main` workflow by hand, it'll fail.
=> [HOTFIX] Don't detect changes when base commit undefined

modules/nf-neuro/preproc/eddy/main.nf, modules/nf-neuro/preproc/topup/main.nf, modules/nf-neuro/preproc/topup/tests/main.nf.test, modules/nf-neuro/preproc/topup/tests/main.nf.test.snap
Setting the `val(config_topup)` as the input for the config file made `topup` run only once for all subjects. The test didn't catch this since we only tested with a single subject. Setting the input to `each config_topup` solves the issue.
=> Change input definition for the topup config file.

modules/nf-neuro/io/readbids/main.nf, modules/nf-neuro/io/readbids/meta.yml, modules/nf-neuro/io/readbids/tests/main.nf.test, subworkflows/nf-neuro/io_bids/main.nf, subworkflows/nf-neuro/io_bids/meta.yml, subworkflows/nf-neuro/io_bids/tests/main.nf.test, subworkflows/nf-neuro/io_bids/tests/main.nf.test.snap, subworkflows/nf-neuro/io_bids/tests/nextflow.config, subworkflows/nf-neuro/io_bids/tests/tags.yml
New subworkflow to cover the gap between the `json` file outputted by `IO_READBIDS` and usable `nextflow channels`. It uses all currently collected files from `scil_bids_validate.py`, but should be adapted in future pipelines to meet the specific file requirements.
**Tests are not super informative since there aren't actual files in the test data.**
=> Subworkflow to transfer BIDS `.json` to `nextflow channels`

subworkflows/nf-neuro/preproc_dwi/main.nf, subworkflows/nf-neuro/preproc_dwi/meta.yml, subworkflows/nf-neuro/preproc_dwi/tests/main.nf.test.snap, subworkflows/nf-neuro/topup_eddy/main.nf, subworkflows/nf-neuro/topup_eddy/meta.yml, subworkflows/nf-neuro/tractoflow/tests/main.nf.test.snap
To use the QC files at the end of a pipeline, we need to collect them through all of the subworkflows so that they are moved up to the pipeline level. I added an empty channel at the beginning of each subworkflows, and mix the qc files in them for modules that already have a QC.
=> Add channel to collect multiqc files in `preproc_dwi` and `topup_eddy`

.devcontainer/devops/Dockerfile, .devcontainer/devops/devcontainer.json, .devcontainer/prototyping/devcontainer.json
There is a memory leak in the **docker-in-docker** extension used to enable `docker run` inside of the devcontainer. It is caused by the **docker compose** sub-command, which we do not use. This PR disables it.
Also, the previous way of syncing the **bash history** between runs of the devcontainer is not working anymore. This fixes it with the method described [here](https://code.visualstudio.com/remote/advancedcontainers/persist-bash-history).
**The PR changes some volumes that get attached to the devcontainer. The old ones will have to be removed manually. It may be good to delete the complete devcontainer and volumes as well.**
This may be only related to installation with **Docker Desktop**, and may be restricted to Linux as well, I can't say. But running any devcontainer on my laptop …
=> Hotfix - devcontainer

modules/nf-neuro/preproc/normalize/meta.yml, modules/nf-neuro/registration/synthregistration/meta.yml, subworkflows/nf-neuro/registration/meta.yml, subworkflows/nf-neuro/tractoflow/meta.yml
Some characters in a couple of `meta.yml` files were making the build of the documentation website fail. Those fixes solve the issue.
Linked to https://github.com/scilus/nf-neuro-documentation/pull/24
=> Fix meta for proper build of documentation site with versioning

.devcontainer/devops/devcontainer.json, .github/reviewers.yml
The devcontainer build fails because some features have changed **URL** (switched from `contrib` to `extra`)
=> [HOTFIX] Update deprecated devcontainer features

modules/nf-neuro/tractogram/removeinvalid/meta.yml
Simply suggesting a rephrasing as this module does not register any tractogram. From what I can see, this sentence was a copy-paste from the registration/tractogram module.
=> [DOC] Documentation fix

modules/nf-neuro/image/resample/main.nf, modules/nf-neuro/image/resample/tests/main.nf.test.snap, subworkflows/nf-neuro/preproc_dwi/main.nf, subworkflows/nf-neuro/preproc_dwi/tests/main.nf.test.snap, subworkflows/nf-neuro/preproc_t1/tests/main.nf.test.snap
This is not a huge bug, but in rare cases, the interpolation of the mask when resampling will give a slightly different resampling, which will make the header non-compatible in future steps of a pipeline. By setting the resampled B0 as a reference, we should be able to avoid those rare cases.
A bit hard to do unless you have this rare case, but see https://github.com/scilus/nf-pediatric/issues/59
**[DONE] This was fix in scilpy, waiting for the next release to update the container**
=> FIX: Add resampled b0 as ref for mask resampling in `preproc_dwi`

.github/workflows/test_component.yml
There is an error in the test workflow, where `gawk` is missing for a step to complete successfully.
Launch any PR that launches any tests.
=> [HOTFIX] add extra step to install gawk
